### ISSUE TITLE
comma seprate not working

### ISSUE THREAD

**Issue by Panda12o8** [cturra/docker-ntp#14]
"""
version: '3.4'

services:
  ntp:
    build: .
    image: cturra/ntp:latest
    container_name: ntp
    restart: always
    ports:
      - 123:123/udp
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE
      - SYS_TIME
    environment:
      - NTP_SERVERS="ntp1.aliyun.com,ntp2.aliyun.com,ntp3.aliyun.com,ntp4.aliyun.com,ntp5.aliyun.com,ntp6.aliyun.com,ntp7.aliyun.com"
"""
after cmd "docker exec  ntp ntpctl -s all" the result shows 
"""
0/1 peers valid, clock unsynced, clock offset is -22145.517ms

peer
   wt tl st  next  poll          offset       delay      jitter
not resolved ntp1.aliyun.comserver ntp2.aliyun.comserver ntp3.aliyun.comserver
    1  2  -   14s   15s             ---- peer not valid ----
"""

**Comment by cturra** [comment]
it looks like the issue is the quotes around the ntp string in your `docker-compose` file. i reproduced the same issue locally and these were the resulting servers in the containers`ntpd.conf`:

```
# time servers provided by NTP_SERVER environment variables.
server "ntp1.aliyun.com
server ntp2.aliyun.com
server ntp3.aliyun.com
server ntp4.aliyun.com
server ntp5.aliyun.com
server ntp6.aliyun.com
server ntp7.aliyun.com"
```

instead, if you update the `NTP_SERVERS` line in your `docker-compose.yml` file to the following, you will get the results you expect (notice i have removed the `"` from before and after the list of ntp servers):

```
- NTP_SERVERS=ntp1.aliyun.com,ntp2.aliyun.com,ntp3.aliyun.com,ntp4.aliyun.com,ntp5.aliyun.com,ntp6.aliyun.com,ntp7.aliyun.com
```

hope that gets you pointed in the right direction.

**Comment by cturra** [comment]
i've also updated the README to make this a little more clear. thanks for catching this :)

 => https://github.com/cturra/docker-ntp/commit/2b3d7a509b56b6444b7cf80abde66c2dba2e93b7

**Comment by cturra** [comment]
^ after thinking about this more, i realized there was no reason why the startup script couldn't evaluate each ntp server string and strip quotes found. that's now been implemented. 

relying on documentation and users to know isn't ideal! 😄 

thanks again for sharing your experience with me.
